<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('product_specifications', function (Blueprint $table) {
            $table->increments('specs_id');
            $table->unsignedBigInteger('product_id');
            $table->string('specs_name');
            $table->string('specs_value');
            // Add foreign key constraint
            $table->foreign('product_id')->references('product_id')->on('products')->onDelete('cascade');
        });
        DB::table('product_specifications')->insert([
            [
                'specs_id' => 36,
                'product_id' => 2755641,
                'specs_name' => 'Dimensions',
                'specs_value' => '1x2x4cm',
            ],
            ['specs_id' => 37, 'product_id' => 2755641, 'specs_name' => 'Weights', 'specs_value' => '1kg', ],
            ['specs_id' => 68, 'product_id' => 2755647, 'specs_name' => 'Width', 'specs_value' => '1x2x4cm'],
            ['specs_id' => 122, 'product_id' => 2755720, 'specs_name' => 'Cores', 'specs_value' => '10'],
            ['specs_id' => 123, 'product_id' => 2755720, 'specs_name' => 'Threads', 'specs_value' => '10'],
            ['specs_id' => 124, 'product_id' => 2755720, 'specs_name' => 'Base Clock Speed', 'specs_value' => '3.7 GHz'],
            ['specs_id' => 125, 'product_id' => 2755720, 'specs_name' => 'Max Turbo Boost Speed', 'specs_value' => '5.3 GHz'],
            ['specs_id' => 126, 'product_id' => 2755721, 'specs_name' => 'Cores', 'specs_value' => '16'],
            ['specs_id' => 127, 'product_id' => 2755721, 'specs_name' => 'Threads', 'specs_value' => '32'],
            ['specs_id' => 128, 'product_id' => 2755721, 'specs_name' => 'Base Clock Speed', 'specs_value' => '3.4 GHz'],
            ['specs_id' => 129, 'product_id' => 2755721, 'specs_name' => 'Max Boost Speed', 'specs_value' => '4.9 GHz'],
            ['specs_id' => 130, 'product_id' => 2755723, 'specs_name' => 'Cores', 'specs_value' => '8'],
            ['specs_id' => 131, 'product_id' => 2755723, 'specs_name' => 'Threads', 'specs_value' => '16'],
            ['specs_id' => 132, 'product_id' => 2755723, 'specs_name' => 'Base Clock Speed', 'specs_value' => '3.6hz'],
            ['specs_id' => 133, 'product_id' => 2755723, 'specs_name' => 'Max Turbo Boost Speed', 'specs_value' => '5.0 GHz'],
            ['specs_id' => 134, 'product_id' => 2755724, 'specs_name' => 'Cores', 'specs_value' => '8'],
            ['specs_id' => 135, 'product_id' => 2755724, 'specs_name' => 'Threads', 'specs_value' => '16'],
            ['specs_id' => 136, 'product_id' => 2755724, 'specs_name' => 'Base Clock Speed', 'specs_value' => '3.8 GHz'],
            ['specs_id' => 137, 'product_id' => 2755724, 'specs_name' => 'Max Boost Speed', 'specs_value' => '4.7 GHz'],
            ['specs_id' => 138, 'product_id' => 2755725, 'specs_name' => 'Cores', 'specs_value' => '6'],
            ['specs_id' => 139, 'product_id' => 2755725, 'specs_name' => 'Threads', 'specs_value' => '12'],
            ['specs_id' => 140, 'product_id' => 2755725, 'specs_name' => 'Base Clock Speed', 'specs_value' => '3.9 GHz'],
            ['specs_id' => 141, 'product_id' => 2755725, 'specs_name' => 'Max Turbo Boost Speed', 'specs_value' => '4.9 GHz'],
            ['specs_id' => 142, 'product_id' => 2755726, 'specs_name' => 'Chipset', 'specs_value' => 'AMD X570'],
            ['specs_id' => 143, 'product_id' => 2755726, 'specs_name' => 'Form Factor', 'specs_value' => 'ATX'],
            ['specs_id' => 144, 'product_id' => 2755726, 'specs_name' => 'Socket', 'specs_value' => 'AM4'],
            ['specs_id' => 145, 'product_id' => 2755726, 'specs_name' => 'Memory Slots', 'specs_value' => '4 x DIMM, DDR4'],
            ['specs_id' => 146, 'product_id' => 2755726, 'specs_name' => 'Expansion Slots', 'specs_value' => '4 x DIMM, DDR4 Expansion Slots: PCIe 4.0 x16, PCIe 4.0 x8, PCIe 4.0 x4'],
            ['specs_id' => 147, 'product_id' => 2755727, 'specs_name' => 'Chipset', 'specs_value' => 'Intel Z590'],
            ['specs_id' => 148, 'product_id' => 2755727, 'specs_name' => 'Form Factor', 'specs_value' => 'ATX'],
            ['specs_id' => 149, 'product_id' => 2755727, 'specs_name' => 'Socket', 'specs_value' => 'LGA 1200'],
            ['specs_id' => 150, 'product_id' => 2755727, 'specs_name' => 'Memory Slots', 'specs_value' => '4 x DIMM, DDR4'],
            ['specs_id' => 151, 'product_id' => 2755727, 'specs_name' => 'Expansion Slots', 'specs_value' => 'PCIe 4.0 x16, PCIe 3.0 x16, PCIe 3.0 x1'],
            ['specs_id' => 152, 'product_id' => 2755728, 'specs_name' => 'Chipset', 'specs_value' => 'AMD B550'],
            ['specs_id' => 153, 'product_id' => 2755728, 'specs_name' => 'Form Factor', 'specs_value' => 'ATX'],
            ['specs_id' => 154, 'product_id' => 2755728, 'specs_name' => 'Socket', 'specs_value' => 'AM4'],
            ['specs_id' => 155, 'product_id' => 2755728, 'specs_name' => 'Memory Slot', 'specs_value' => '4 x DIMM, DDR4'],
            ['specs_id' => 156, 'product_id' => 2755728, 'specs_name' => 'Expansion Slots', 'specs_value' => 'PCIe 4.0 x16, PCIe 3.0 x16, PCIe 3.0 x1'],
            ['specs_id' => 157, 'product_id' => 2755729, 'specs_name' => 'Chipset', 'specs_value' => 'Intel Z590'],
            ['specs_id' => 158, 'product_id' => 2755729, 'specs_name' => 'Form Factor', 'specs_value' => 'ATX'],
            ['specs_id' => 159, 'product_id' => 2755729, 'specs_name' => 'Socket', 'specs_value' => 'LGA 1200'],
            ['specs_id' => 160, 'product_id' => 2755729, 'specs_name' => 'Expansion Slot', 'specs_value' => 'PCIe 4.0 x16, PCIe 3.0 x16, PCIe 3.0 x1'],
            ['specs_id' => 161, 'product_id' => 2755730, 'specs_name' => 'Chipset', 'specs_value' => 'AMD B550'],
            ['specs_id' => 162, 'product_id' => 2755730, 'specs_name' => 'Form Factor', 'specs_value' => 'Micro ATX'],
            ['specs_id' => 163, 'product_id' => 2755730, 'specs_name' => 'Socket', 'specs_value' => 'AM4'],
            ['specs_id' => 164, 'product_id' => 2755730, 'specs_name' => 'Memory Slots', 'specs_value' => '4 x DIMM, DDR4'],
            ['specs_id' => 165, 'product_id' => 2755730, 'specs_name' => 'Expansion Slots', 'specs_value' => 'PCIe 4.0 x16, PCIe 3.0 x16, PCIe 3.0 x1'],
            ['specs_id' => 166, 'product_id' => 2755731, 'specs_name' => 'Capacity', 'specs_value' => '16GB (2 x 8GB)'],
            ['specs_id' => 167, 'product_id' => 2755731, 'specs_name' => 'Type', 'specs_value' => 'DDR4'],
            ['specs_id' => 168, 'product_id' => 2755731, 'specs_name' => 'Speed', 'specs_value' => '3200MHz'],
            ['specs_id' => 169, 'product_id' => 2755731, 'specs_name' => 'CAS Latency', 'specs_value' => '16'],
            ['specs_id' => 170, 'product_id' => 2755732, 'specs_name' => 'Capacity', 'specs_value' => '32GB (2 x 16GB)'],
            ['specs_id' => 171, 'product_id' => 2755732, 'specs_name' => 'Type', 'specs_value' => 'DDR4'],
            ['specs_id' => 172, 'product_id' => 2755732, 'specs_name' => 'Speed', 'specs_value' => '3600MHz'],
            ['specs_id' => 173, 'product_id' => 2755732, 'specs_name' => 'CAS Latency', 'specs_value' => '16'],
            ['specs_id' => 174, 'product_id' => 2755733, 'specs_name' => 'Capacity', 'specs_value' => '8gb'],
            ['specs_id' => 175, 'product_id' => 2755733, 'specs_name' => 'Type', 'specs_value' => 'DDR4'],
            ['specs_id' => 176, 'product_id' => 2755733, 'specs_name' => 'Speed', 'specs_value' => '3200MHz'],
            ['specs_id' => 177, 'product_id' => 2755733, 'specs_name' => 'CAS Latency', 'specs_value' => '16'],
            ['specs_id' => 178, 'product_id' => 2755734, 'specs_name' => 'Capacity', 'specs_value' => '16GB (2 x 8GB)'],
            ['specs_id' => 179, 'product_id' => 2755734, 'specs_name' => 'Type', 'specs_value' => 'DDR4'],
            ['specs_id' => 180, 'product_id' => 2755734, 'specs_name' => 'Speed', 'specs_value' => '3600MHz'],
            ['specs_id' => 181, 'product_id' => 2755734, 'specs_name' => 'CAS Latency', 'specs_value' => '16'],
            ['specs_id' => 182, 'product_id' => 2755735, 'specs_name' => 'Capacity', 'specs_value' => '16GB (2 x 8GB)'],
            ['specs_id' => 183, 'product_id' => 2755735, 'specs_name' => 'Type', 'specs_value' => 'DDR4'],
            ['specs_id' => 184, 'product_id' => 2755735, 'specs_name' => 'Speed', 'specs_value' => '3000MHz'],
            ['specs_id' => 185, 'product_id' => 2755735, 'specs_name' => 'CAS Latency', 'specs_value' => '16'],
            ['specs_id' => 186, 'product_id' => 2755736, 'specs_name' => 'GPU Architecture', 'specs_value' => 'Ampere'],
            ['specs_id' => 187, 'product_id' => 2755736, 'specs_name' => 'VRAM', 'specs_value' => '10GB GDDR6X'],
            ['specs_id' => 188, 'product_id' => 2755736, 'specs_name' => 'Boost Clock', 'specs_value' => '1710 MHz'],
            ['specs_id' => 189, 'product_id' => 2755736, 'specs_name' => 'Memory Interface', 'specs_value' => ' MHz Memory Interface: 320-bit'],
            ['specs_id' => 190, 'product_id' => 2755737, 'specs_name' => 'GPU Architecture', 'specs_value' => 'RDNA 2'],
            ['specs_id' => 191, 'product_id' => 2755737, 'specs_name' => 'VRAM', 'specs_value' => '16GB GDDR6'],
            ['specs_id' => 192, 'product_id' => 2755737, 'specs_name' => 'Boost Clock', 'specs_value' => '2250 MHz'],
            ['specs_id' => 193, 'product_id' => 2755737, 'specs_name' => 'Memory Interface', 'specs_value' => '256-bit'],
            ['specs_id' => 194, 'product_id' => 2755738, 'specs_name' => 'GPU Architecture', 'specs_value' => 'Turing'],
            ['specs_id' => 195, 'product_id' => 2755738, 'specs_name' => 'VRAM', 'specs_value' => '6GB GDDR6'],
            ['specs_id' => 196, 'product_id' => 2755738, 'specs_name' => 'Boost Clock', 'specs_value' => '1785 MHz'],
            ['specs_id' => 197, 'product_id' => 2755738, 'specs_name' => 'Memory Interface', 'specs_value' => '192-bit'],
            ['specs_id' => 198, 'product_id' => 2755739, 'specs_name' => 'GPU Architecture', 'specs_value' => 'RDNA 2'],
            ['specs_id' => 199, 'product_id' => 2755739, 'specs_name' => 'VRAM', 'specs_value' => '12GB GDDR6'],
            ['specs_id' => 200, 'product_id' => 2755739, 'specs_name' => 'Boost Clock', 'specs_value' => '2581 MHz'],
            ['specs_id' => 201, 'product_id' => 2755739, 'specs_name' => 'Memory Interfac', 'specs_value' => '192-bit'],
            ['specs_id' => 202, 'product_id' => 2755740, 'specs_name' => 'Capacity', 'specs_value' => '1TB'],
            ['specs_id' => 203, 'product_id' => 2755740, 'specs_name' => 'Interface', 'specs_value' => 'PCIe Gen 3.0 x4, NVMe 1.3'],
            ['specs_id' => 204, 'product_id' => 2755740, 'specs_name' => 'Read Speed', 'specs_value' => ' Up to 3,500 MB/s'],
            ['specs_id' => 205, 'product_id' => 2755740, 'specs_name' => 'Write Speed', 'specs_value' => ' Up to 3,300 MB/s'],
            ['specs_id' => 206, 'product_id' => 2755741, 'specs_name' => 'Capacity', 'specs_value' => '500GB'],
            ['specs_id' => 207, 'product_id' => 2755741, 'specs_name' => 'Interface', 'specs_value' => ' PCIe Gen 3.0 x4, NVMe 1.3'],
            ['specs_id' => 208, 'product_id' => 2755741, 'specs_name' => 'Read Speed', 'specs_value' => 'Up to 3,470 MB/s'],
            ['specs_id' => 209, 'product_id' => 2755741, 'specs_name' => 'Write Speed', 'specs_value' => 'Up to 2,600 MB/s'],
            ['specs_id' => 210, 'product_id' => 2755742, 'specs_name' => 'Capacity', 'specs_value' => '2TB'],
            ['specs_id' => 211, 'product_id' => 2755742, 'specs_name' => 'Interface', 'specs_value' => 'SATA 6Gb/s'],
            ['specs_id' => 212, 'product_id' => 2755742, 'specs_name' => 'Speed', 'specs_value' => ' 7200 RPM'],
            ['specs_id' => 213, 'product_id' => 2755742, 'specs_name' => 'Cache', 'specs_value' => '256MB'],
            ['specs_id' => 214, 'product_id' => 2755743, 'specs_name' => 'Capacity', 'specs_value' => '1TB'],
            ['specs_id' => 215, 'product_id' => 2755743, 'specs_name' => 'Interface', 'specs_value' => 'SATA 6Gb/s'],
            ['specs_id' => 216, 'product_id' => 2755743, 'specs_name' => 'Read Speed', 'specs_value' => 'Up to 560 MB/s'],
            ['specs_id' => 217, 'product_id' => 2755743, 'specs_name' => 'Write Speed', 'specs_value' => 'Up to 510 MB/s'],
            ['specs_id' => 222, 'product_id' => 2755745, 'specs_name' => 'Capacity', 'specs_value' => '500GB'],
            ['specs_id' => 223, 'product_id' => 2755745, 'specs_name' => 'Interface', 'specs_value' => 'PCIe Gen 3.0 x4, NVMe 1.3'],
            ['specs_id' => 224, 'product_id' => 2755745, 'specs_name' => 'Read Speed', 'specs_value' => 'Up to 2,200 MB/s'],
            ['specs_id' => 225, 'product_id' => 2755745, 'specs_name' => 'Write Spee', 'specs_value' => 'Up to 2,000 MB/s'],
            ['specs_id' => 226, 'product_id' => 2755746, 'specs_name' => 'Wattage', 'specs_value' => '750W'],
            ['specs_id' => 227, 'product_id' => 2755746, 'specs_name' => 'Efficiency', 'specs_value' => '80 Plus Gold certified'],
            ['specs_id' => 228, 'product_id' => 2755746, 'specs_name' => 'Modular', 'specs_value' => 'Fully modular design'],
            ['specs_id' => 229, 'product_id' => 2755746, 'specs_name' => 'Fan', 'specs_value' => '135mm Zero RPM fan mode for silent operation'],
            ['specs_id' => 230, 'product_id' => 2755746, 'specs_name' => 'Connectors', 'specs_value' => 'Multiple PCIe and SATA connectors for high-end components'],
            ['specs_id' => 231, 'product_id' => 2755747, 'specs_name' => 'Wattage', 'specs_value' => '850W'],
            ['specs_id' => 232, 'product_id' => 2755747, 'specs_name' => 'Efficiency', 'specs_value' => '80 Plus Gold certified'],
            ['specs_id' => 233, 'product_id' => 2755747, 'specs_name' => 'Modular', 'specs_value' => 'Fully modular cables for easy cable management'],
            ['specs_id' => 234, 'product_id' => 2755747, 'specs_name' => 'Fan', 'specs_value' => '130mm hydraulic dynamic bearing fan for quiet '],
            ['specs_id' => 235, 'product_id' => 2755747, 'specs_name' => 'Connectors', 'specs_value' => 'Multiple PCIe and SATA connectors for high-end components'],
            ['specs_id' => 236, 'product_id' => 2755748, 'specs_name' => 'Wattage', 'specs_value' => '650W'],
            ['specs_id' => 237, 'product_id' => 2755748, 'specs_name' => 'Efficiency', 'specs_value' => '80 Plus Gold certified'],
            ['specs_id' => 238, 'product_id' => 2755748, 'specs_name' => 'Modular', 'specs_value' => 'Fully modular design'],
            ['specs_id' => 239, 'product_id' => 2755748, 'specs_name' => 'Fan', 'specs_value' => '120mm Fluid Dynamic Bearing fan for quiet cooling'],
            ['specs_id' => 240, 'product_id' => 2755748, 'specs_name' => 'Connectors', 'specs_value' => 'Ample connectors for various components'],
            ['specs_id' => 241, 'product_id' => 2755749, 'specs_name' => 'Wattage', 'specs_value' => '750W'],
            ['specs_id' => 242, 'product_id' => 2755749, 'specs_name' => 'Efficiency', 'specs_value' => '80 Plus Gold certified'],
            ['specs_id' => 243, 'product_id' => 2755749, 'specs_name' => 'Modular', 'specs_value' => 'Fully modular design'],
            ['specs_id' => 244, 'product_id' => 2755749, 'specs_name' => 'Fan', 'specs_value' => ' 140mm RGB fan with intelligent zero RPM mode'],
            ['specs_id' => 245, 'product_id' => 2755749, 'specs_name' => 'Connectors', 'specs_value' => 'Multiple PCIe and SATA connectors for high-end components'],
            ['specs_id' => 246, 'product_id' => 2755750, 'specs_name' => 'Wattage', 'specs_value' => '850W'],
            ['specs_id' => 247, 'product_id' => 2755750, 'specs_name' => 'Efficiency', 'specs_value' => '80 Plus Gold certified'],
            ['specs_id' => 248, 'product_id' => 2755750, 'specs_name' => 'Modular', 'specs_value' => ' Fully modular design'],
            ['specs_id' => 249, 'product_id' => 2755750, 'specs_name' => 'Fan', 'specs_value' => '135mm Silent Wings 3 fan with an advanced fan controller'],
            ['specs_id' => 250, 'product_id' => 2755750, 'specs_name' => 'Connectors', 'specs_value' => 'Comprehensive set of connectors for high-performance components'],
            ['specs_id' => 251, 'product_id' => 2755751, 'specs_name' => 'Form Factor', 'specs_value' => 'Mid-Tower'],
            ['specs_id' => 252, 'product_id' => 2755751, 'specs_name' => 'Motherboard Support', 'specs_value' => 'ATX, Micro-ATX, Mini-ITX'],
            ['specs_id' => 253, 'product_id' => 2755751, 'specs_name' => 'Cooling', 'specs_value' => 'Multiple fan mounts and radiator support'],
            ['specs_id' => 254, 'product_id' => 2755751, 'specs_name' => 'Drive Bays', 'specs_value' => '2x 2.5" SSD, 2x 3.5" HDD'],
            ['specs_id' => 255, 'product_id' => 2755751, 'specs_name' => 'Cable Management', 'specs_value' => 'Built-in cable routing channels'],
            ['specs_id' => 256, 'product_id' => 2755752, 'specs_name' => 'Form Factor', 'specs_value' => 'Full-Tower'],
            ['specs_id' => 257, 'product_id' => 2755752, 'specs_name' => 'Motherboard Support', 'specs_value' => 'ATX, Micro-ATX, Mini-ITX'],
            ['specs_id' => 258, 'product_id' => 2755752, 'specs_name' => 'Cooling', 'specs_value' => ' Includes 3x 120mm RGB fans, additional fan and radiator support'],
            ['specs_id' => 259, 'product_id' => 2755752, 'specs_name' => 'Drive Bays', 'specs_value' => ' 2x 3.5" HDD, 4x 2.5" SSD'],
            ['specs_id' => 260, 'product_id' => 2755752, 'specs_name' => 'Cable Management', 'specs_value' => 'Ample space for cable routing and tie-downs'],
            ['specs_id' => 261, 'product_id' => 2755753, 'specs_name' => 'Form Factor', 'specs_value' => 'Mid-Tower'],
            ['specs_id' => 262, 'product_id' => 2755753, 'specs_name' => 'Motherboard Support', 'specs_value' => ' ATX, Micro-ATX, Mini-ITX'],
            ['specs_id' => 263, 'product_id' => 2755753, 'specs_name' => 'Cooling', 'specs_value' => 'Optimized front panel mesh for increased airflow'],
            ['specs_id' => 264, 'product_id' => 2755753, 'specs_name' => 'Drive Bays', 'specs_value' => '2x 3.5" HDD, 3x 2.5" SSD'],
            ['specs_id' => 265, 'product_id' => 2755753, 'specs_name' => 'Cable Management', 'specs_value' => 'Velcro straps and space behind the motherboard tray'],
            ['specs_id' => 266, 'product_id' => 2755754, 'specs_name' => 'Form Factor', 'specs_value' => 'Mid-Tower'],
            ['specs_id' => 267, 'product_id' => 2755754, 'specs_name' => 'Motherboard Support', 'specs_value' => ' ATX, Micro-ATX, Mini-ITX'],
            ['specs_id' => 268, 'product_id' => 2755754, 'specs_name' => 'Cooling', 'specs_value' => 'Mesh front panel with 3x 120mm ARGB fans included, additional fan and radiator support'],
            ['specs_id' => 269, 'product_id' => 2755754, 'specs_name' => 'Drive Bays', 'specs_value' => '2x 3.5" HDD, 2x 2.5" SSD'],
            ['specs_id' => 270, 'product_id' => 2755754, 'specs_name' => 'Cable Management', 'specs_value' => 'Multiple cable routing options and covers'],
            ['specs_id' => 271, 'product_id' => 2755755, 'specs_name' => 'Form Factor', 'specs_value' => 'Mid-Tower'],
            ['specs_id' => 272, 'product_id' => 2755755, 'specs_name' => 'Motherboard Support', 'specs_value' => 'ATX, Micro-ATX, Mini-ITX'],
            ['specs_id' => 273, 'product_id' => 2755755, 'specs_name' => 'Cooling', 'specs_value' => 'Front mesh panel with pre-installed 2x 120mm fans, additional fan and radiator support'],
            ['specs_id' => 274, 'product_id' => 2755755, 'specs_name' => 'Drive Bays', 'specs_value' => '2x 3.5" HDD, 2x 2.5" SSD'],
            ['specs_id' => 275, 'product_id' => 2755755, 'specs_name' => 'Cable Management', 'specs_value' => 'Velcro cable ties and multiple routing options'],
            ['specs_id' => 276, 'product_id' => 2755756, 'specs_name' => 'Type', 'specs_value' => 'Air cooler'],
            ['specs_id' => 277, 'product_id' => 2755756, 'specs_name' => 'Fan Size', 'specs_value' => '140mm'],
            ['specs_id' => 278, 'product_id' => 2755756, 'specs_name' => 'Heatpipes', 'specs_value' => '6 heatpipes'],
            ['specs_id' => 279, 'product_id' => 2755756, 'specs_name' => 'Compatibility', 'specs_value' => 'Supports a wide range of CPU sockets'],
            ['specs_id' => 280, 'product_id' => 2755757, 'specs_name' => 'Type', 'specs_value' => ' Liquid cooler'],
            ['specs_id' => 281, 'product_id' => 2755757, 'specs_name' => 'Radiator Size', 'specs_value' => '240mm'],
            ['specs_id' => 282, 'product_id' => 2755757, 'specs_name' => 'Fan Size', 'specs_value' => '120mm'],
            ['specs_id' => 283, 'product_id' => 2755757, 'specs_name' => 'RGB Lighting', 'specs_value' => 'Customizable RGB lighting effects'],
            ['specs_id' => 284, 'product_id' => 2755758, 'specs_name' => 'Type', 'specs_value' => ' Air cooler'],
            ['specs_id' => 285, 'product_id' => 2755758, 'specs_name' => 'Fan Size', 'specs_value' => '120mm'],
            ['specs_id' => 286, 'product_id' => 2755758, 'specs_name' => 'Heatpipes', 'specs_value' => '4 heatpipes'],
            ['specs_id' => 287, 'product_id' => 2755758, 'specs_name' => 'Compatibility', 'specs_value' => ' Supports a wide range of CPU sockets'],
            ['specs_id' => 288, 'product_id' => 2755759, 'specs_name' => 'Type', 'specs_value' => 'Liquid cooler'],
            ['specs_id' => 289, 'product_id' => 2755759, 'specs_name' => 'Radiator Size', 'specs_value' => '280mm'],
            ['specs_id' => 290, 'product_id' => 2755759, 'specs_name' => 'Fan Size', 'specs_value' => '140mm'],
            ['specs_id' => 291, 'product_id' => 2755759, 'specs_name' => 'RGB Lighting', 'specs_value' => 'Customizable RGB lighting effects'],
            ['specs_id' => 292, 'product_id' => 2755760, 'specs_name' => 'Type', 'specs_value' => 'Air cooler'],
            ['specs_id' => 293, 'product_id' => 2755760, 'specs_name' => 'Fan Size', 'specs_value' => '120mm'],
            ['specs_id' => 294, 'product_id' => 2755760, 'specs_name' => 'Heatpipes', 'specs_value' => '4 heatpipes'],
            ['specs_id' => 295, 'product_id' => 2755760, 'specs_name' => 'Compatibility', 'specs_value' => 'Supports a wide range of CPU sockets'],
            ['specs_id' => 296, 'product_id' => 2755761, 'specs_name' => 'DPI', 'specs_value' => '100-25,600 DPI'],
            ['specs_id' => 297, 'product_id' => 2755761, 'specs_name' => 'Programmable Buttons', 'specs_value' => '11 programmable buttons'],
            ['specs_id' => 298, 'product_id' => 2755761, 'specs_name' => 'Connectivity', 'specs_value' => ' Wired (USB)'],
            ['specs_id' => 299, 'product_id' => 2755761, 'specs_name' => 'Ergonomics', 'specs_value' => 'Customizable weight and balance'],
            ['specs_id' => 300, 'product_id' => 2755762, 'specs_name' => 'Key Switches', 'specs_value' => 'Razer Green mechanical switches'],
            ['specs_id' => 301, 'product_id' => 2755762, 'specs_name' => 'Backlighting', 'specs_value' => 'Razer Chroma RGB lighting'],
            ['specs_id' => 302, 'product_id' => 2755762, 'specs_name' => 'Connectivity', 'specs_value' => 'Wired (USB)'],
            ['specs_id' => 303, 'product_id' => 2755762, 'specs_name' => 'Macro Keys', 'specs_value' => 'Fully programmable macro keys'],
            ['specs_id' => 304, 'product_id' => 2755763, 'specs_name' => 'Wireless Connectivity', 'specs_value' => ' 2.4GHz wireless with low latency'],
            ['specs_id' => 305, 'product_id' => 2755763, 'specs_name' => 'Battery Life', 'specs_value' => 'Up to 24 hours'],
            ['specs_id' => 306, 'product_id' => 2755763, 'specs_name' => 'Compatibility', 'specs_value' => 'PC, PlayStation, Xbox, and Nintendo Switch'],
            ['specs_id' => 307, 'product_id' => 2755763, 'specs_name' => 'Microphone', 'specs_value' => 'Retractable ClearCast microphone'],
            ['specs_id' => 308, 'product_id' => 2755764, 'specs_name' => 'Key Switches', 'specs_value' => 'HyperX Red mechanical switches'],
            ['specs_id' => 309, 'product_id' => 2755764, 'specs_name' => 'Backlighting', 'specs_value' => 'Customizable RGB lighting'],
            ['specs_id' => 310, 'product_id' => 2755764, 'specs_name' => 'Connectivity', 'specs_value' => 'Wired (USB)'],
            ['specs_id' => 311, 'product_id' => 2755764, 'specs_name' => 'Anti-Ghosting', 'specs_value' => 'N-Key rollover'],
            ['specs_id' => 312, 'product_id' => 2755765, 'specs_name' => 'Wi-Fi Standard', 'specs_value' => 'Wi-Fi 6 (802.11ax)'],
            ['specs_id' => 313, 'product_id' => 2755765, 'specs_name' => 'Speed', 'specs_value' => 'Up to 6000Mbps'],
            ['specs_id' => 314, 'product_id' => 2755765, 'specs_name' => 'Ethernet Ports', 'specs_value' => '8x Gigabit LAN ports, 1x Gigabit WAN port'],
            ['specs_id' => 315, 'product_id' => 2755765, 'specs_name' => 'Antennas', 'specs_value' => '8 high-gain antennas'],
            ['specs_id' => 316, 'product_id' => 2755766, 'specs_name' => 'Wi-Fi Standard', 'specs_value' => '802.11ac'],
            ['specs_id' => 317, 'product_id' => 2755766, 'specs_name' => 'Speed', 'specs_value' => 'Up to 1900Mbps'],
            ['specs_id' => 318, 'product_id' => 2755766, 'specs_name' => 'Ethernet Ports', 'specs_value' => '4x Gigabit LAN ports, 1x Gigabit WAN port'],
            ['specs_id' => 319, 'product_id' => 2755766, 'specs_name' => 'Antennas', 'specs_value' => '3 high-powered antennas'],
            ['specs_id' => 320, 'product_id' => 2755767, 'specs_name' => 'Wi-Fi Standard', 'specs_value' => 'Wi-Fi 6 (802.11ax)'],
            ['specs_id' => 321, 'product_id' => 2755767, 'specs_name' => 'Speed', 'specs_value' => 'Up to 6000Mbps'],
            ['specs_id' => 322, 'product_id' => 2755767, 'specs_name' => 'Ethernet Ports', 'specs_value' => '8x Gigabit LAN ports, 1x Gigabit WAN port'],
            ['specs_id' => 323, 'product_id' => 2755767, 'specs_name' => 'Antennas', 'specs_value' => '4 external antennas'],
            ['specs_id' => 324, 'product_id' => 2755768, 'specs_name' => 'Wi-Fi Standard', 'specs_value' => '802.11ac'],
            ['specs_id' => 325, 'product_id' => 2755768, 'specs_name' => 'Speed', 'specs_value' => 'Up to 3200Mbps'],
            ['specs_id' => 326, 'product_id' => 2755768, 'specs_name' => 'Ethernet Ports', 'specs_value' => '4x Gigabit LAN ports, 1x Gigabit WAN port'],
            ['specs_id' => 327, 'product_id' => 2755768, 'specs_name' => 'Antennas', 'specs_value' => '4 external antennas'],
            ['specs_id' => 328, 'product_id' => 2755769, 'specs_name' => 'Wi-Fi Standard', 'specs_value' => '802.11ac'],
            ['specs_id' => 329, 'product_id' => 2755769, 'specs_name' => 'Speed', 'specs_value' => 'Up to 2600Mbps'],
            ['specs_id' => 330, 'product_id' => 2755769, 'specs_name' => 'Ethernet Ports', 'specs_value' => '4x Gigabit LAN ports, 1x Gigabit WAN port'],
            ['specs_id' => 331, 'product_id' => 2755769, 'specs_name' => 'Antennas', 'specs_value' => '4 high-gain antennas'],
            
        ]);
        
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('product_specifications');
    }
};
